version: 0.0
os: linux

files:
  - source: app
    destination: /home/stagmtp/marketplace/app
  - source: /index.html
    destination: /var/www/html/
file_exists_behavior: OVERWRITE 

permissions:
  - object: /home/stagmtp/marketplace/app/assets/admin/
    pattern: "*csv*"
    owner: stagmtp
    group: stagmtp
    mode: 777
    type:
      - file    
  - object: /home/stagmtp/marketplace/app
    owner: stagmtp
    group: stagmtp
    mode: 777
    type:
      - directory
  # - object: /home/stagmtp/marketplace/app/assets/admin/img/
  #   pattern: "*offeringImage*"
  #   owner: stagmtp
  #   group: stagmtp
  #   mode: 777
  #   type:
  #     - directory
  # - object: /home/stagmtp/marketplace/app/assets/admin/img/
  #   pattern: "*offeringPhotos*"
  #   owner: stagmtp
  #   group: stagmtp
  #   mode: 777
  #   type:
  #     - directory

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
